apiVersion: v1
kind: ServiceAccount
metadata:
  name: client
---
apiVersion: v1
kind: Service
metadata:
  name: client
  labels:
    app: client
    service: client
spec:
  ports:
  - name: http
    port: 80
  selector:
    app: client
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      serviceAccountName: client
      nodeSelector:
        kubernetes.io/os: linux
      containers:
      - image: cybwan/mtls-egress-demo-client
        imagePullPolicy: Always
        name: client
        command: ["/bin/sleep", "infinity"]
        ports:
        - containerPort: 80
        volumeMounts:
          - name: client-mtls-secret
            mountPath: "/certs"
            readOnly: true
      volumes:
        - name: client-mtls-secret
          secret:
            secretName: client-mtls-secret