apiVersion: v1
kind: ServiceAccount
metadata:
  name: server
---
apiVersion: v1
kind: Service
metadata:
  name: server
  labels:
    app: server
    service: server
spec:
  ports:
  - name: https
    port: 8443
  selector:
    app: server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      serviceAccountName: server
      nodeSelector:
        kubernetes.io/os: linux
      containers:
      - image: cybwan/mtls-egress-demo-server-without-certs
        imagePullPolicy: Always
        name: server
        command: ["/server"]
        ports:
        - containerPort: 8443
        volumeMounts:
          - name: server-mtls-secret
            mountPath: "/certs"
            readOnly: true
      volumes:
        - name: server-mtls-secret
          secret:
            secretName: server-mtls-secret