apiVersion: apps/v1
kind: Deployment
metadata:
  name: pipy-ok-c2
  labels:
    app: pipy-ok-c2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pipy-ok-c2
  template:
    metadata:
      labels:
        app: pipy-ok-c2
    spec:
      containers:
        - name: pipy
          image: flomesh/pipy:0.50.0-146
          ports:
            - name: pipy
              containerPort: 8080
          command:
            - pipy
            - -e
            - |
              pipy()
              .listen(8080)
              .serveHTTP(new Message('Hi, I am from Cluster2 !'))
---
apiVersion: v1
kind: Service
metadata:
  name: pipy-ok
spec:
  ports:
    - name: pipy
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: pipy-ok-c2
---
apiVersion: v1
kind: Service
metadata:
  name: pipy-ok-c2
spec:
  ports:
    - name: pipy
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: pipy-ok-c2